### ISSUE TITLE
UiPath Jenkins Plugin publish Process when created with “Windows” Compatibility Failing

### ISSUE THREAD

**Issue by suryavaranasi9** [jenkinsci/uipath-automation-package-plugin#155]
### Jenkins and plugins versions report

Jenkins: 2.346.4.1

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server 2016

### Reproduction steps

1. Building project / main.xaml in UiPath Studio using Windows compatibility
2. Pushing to Github repository
3. Adding Jenkinsfile to repository
4. Jenkins builds gets started.
5. Project / Package successfully pushed to Orchestrator
6. Going to "Automations" tab option, selecting "Jobs", Clicking "Start" option button
7. Selecting "Process" name, selecting "runtime" and "priority" options, passing necessary arguments.
8. Clicking on "Start" button

### Expected Results

Process to start in UiPath and run the package/project

### Actual Results

We are using Jenkins for deployments, and is using 2.11 version of plugin. Studio's and Orchestrator are on version 22.10.x.
When we are deploying Windows Legacy processes, deployment is being successful and automations are running fine.
But when we are deploying "Windows" processes, deployment is being successful but the automations are failing with an error.

Error message:
RemoteException wrapping System.IO.FileNotFoundException: Could not load file or assembly 'XXXXXX' , Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
at UiPath.Executor.WorkflowLoader.GetWorkflowFromXamlPath(String assemblyName, String xamlPath)
at UiPath.Executor.WorkflowLoader.LoadWorkflow(String xamlPath, String compiledWorkflowAssemblyName)
at UiPath.Executor.WorkflowRuntime.Load(String workflowFile, String compiledWorkflowAssemblyName)
at UiPath.Executor.WorkflowRuntime.Load(String workflowFile)
at UiPath.Executor.RobotRunner.InitWorkflowApplication()
at UiPath.Executor.RobotRunner.ExecuteJob()

**Comment by derrickserbia** [comment]
Hi @suryavaranasi9, our team also uses this plugin and just ran into this error. Were you able to run the process if you Published from Studio and upload the package manually?

**Comment by suryavaranasi9** [comment]
Hi @derrickserbia, YES manual steps are running fine. Publishing from Studio and upload the nuget package to Orch.
